[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = default.csv
; upload_protocol = espota  ; for OTA
; upload_port = 192.168.x.x

lib_deps = 
	bblanchon/ArduinoJson@^7.4.2
	adafruit/Adafruit CCS811 Library@^1.0.0
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit BMP280 Library@^2.3.0
	adafruit/Adafruit SHT31 Library@^2.2.2
	olikraus/U8g2@^2.34.13
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit NeoPixel@^1.15.5
	adafruit/Adafruit TMP117@^1.0.5
	sensirion/Sensirion I2C SHT4x@^1.1.2
	adafruit/Adafruit MAX31865 library@^1.6.2

build_flags = 
    ; ESP type
	-DESP32

    ; Serial stuff
    -DMODULE_SERIAL
	; -D ARDUINO_USB_MODE=1
	; -D ARDUINO_USB_CDC_ON_BOOT=1
	
    ; Outputs
	-DMODULE_WIFI
	-DMODULE_WSERVER
	-DMODULE_NEO_PIXEL
	; -DMODULE_OLED
	; -DMODULE_SERIAL_DEBUG

    ; sensors
	; -DMODULE_SHT31
	; -DMODULE_LDR
	-DMODULE_BMP388
	-DMODULE_TMP117
	-DMODULE_SHT45
	-DMODULE_MAX31865
	-DMAX31865_RREF=441.9
	-DSENSOR_UPDATE_RATE=500
		
    ; pin config
	-DPIN_SDA=1
	-DPIN_SCL=0
	; -DPIN_LDR=17U
	
    ; node settings
	-DDEVICE_ID=3
